version: '3.8'
services:
  db:
    image: 'postgres:latest'
    networks:
      - 'backend'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'exchange'
      PGDATA: '/var/lib/postgresql/data/pgdata'

  app:
    image: 'openjdk:11'
    user: '$UID:$GID'
    volumes:
      - './app:/app'
    working_dir: '/app'
    entrypoint: ['java', '-jar', 'build/libs/exchange-0.0.1-SNAPSHOT.jar']
    networks:
      - 'backend'
    ports:
      - '8080:8080'

  admin:
    image: 'dpage/pgadmin4:latest'
    networks:
      - 'backend'
    ports:
      - '8008:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@exchange.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'

networks:
  backend:
    driver: 'bridge'
    ipam:
      driver: 'default'
      config:
        - subnet: '172.16.0.0/24'
